### ISSUE TITLE
lmmSpline() running time 

### ISSUE THREAD

**Issue by shathab** [abodein/timeOmics_BioC#1]
Thank you for the great package. I was trying to follow the vignette, what is the estimated runtime for lmmSpline(). Because when I run the code below from the vignette, it does not show any results after running it for a long time (>60 min) with no errors or warnings. What would you suggest to solve this issue.

lmms.output <- lmms::lmmSpline(data = data.filtered, time = time,
                        sampleID = rownames(data.filtered), deri = FALSE,
                        basis = "p-spline", numCores = 4, timePredict = 1:9, 
                        keepModels = TRUE)

Thank you for your help in advance!

**Comment by abodein** [comment]
Hi @shathab,
`lmmSpline()` is not so long. It runs a matrix of 1600 genes x (6 timepoints X 5 replicates) within a few seconds.
It can be longer with more variables and/or more timepoints.
I suggest first to focus on variables with a high coefficient of variation (top 1000/2000).
This will speed up your runtime.

**Comment by shathab** [comment]
Thank you for your quick response.  I am following the vignette from the package and still with no luck. I am not getting any results in the console after running the code from the vignette for a very long time. what else would you suggest to do?

Thanks again for your help!

lmms.output <- lmms::lmmSpline(data = data.filtered, time = time,
sampleID = rownames(data.filtered), deri = FALSE,
basis = "p-spline", numCores = 4, timePredict = 1:9,
keepModels = TRUE)

**Comment by abodein** [comment]
Okay, that's strange. What is your `sessionInfo()`? Make sure you have up-to-date packages.

**Comment by shathab** [comment]
> session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       macOS High Sierra 10.13.6   
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Asia                
 date     2020-04-15                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────
 package      * version  date       lib source                            
 assertthat     0.2.1    2019-03-21 [1] CRAN (R 3.6.0)                    
 backports      1.1.6    2020-04-05 [1] CRAN (R 3.6.2)                    
 bitops         1.0-6    2013-08-17 [1] CRAN (R 3.6.0)                    
 broom          0.5.5    2020-02-29 [1] CRAN (R 3.6.0)                    
 callr          3.4.3    2020-03-28 [1] CRAN (R 3.6.2)                    
 caTools        1.18.0   2020-01-17 [1] CRAN (R 3.6.0)                    
 cellranger     1.1.0    2016-07-27 [1] CRAN (R 3.6.0)                    
 cli            2.0.2    2020-02-28 [1] CRAN (R 3.6.0)                    
 colorspace     1.4-1    2019-03-18 [1] CRAN (R 3.6.0)                    
 corpcor        1.6.9    2017-04-01 [1] CRAN (R 3.6.0)                    
 crayon         1.3.4    2017-09-16 [1] CRAN (R 3.6.0)                    
 curl           4.3      2019-12-02 [1] CRAN (R 3.6.0)                    
 DBI            1.1.0    2019-12-15 [1] CRAN (R 3.6.0)                    
 dbplyr         1.4.2    2019-06-17 [1] CRAN (R 3.6.0)                    
 desc           1.2.0    2018-05-01 [1] CRAN (R 3.6.0)                    
 devtools     * 2.3.0    2020-04-10 [1] CRAN (R 3.6.3)                    
 digest         0.6.25   2020-02-23 [1] CRAN (R 3.6.0)                    
 dplyr        * 0.8.5    2020-03-07 [1] CRAN (R 3.6.0)                    
 ellipse        0.4.1    2018-01-05 [1] CRAN (R 3.6.0)                    
 ellipsis       0.3.0    2019-09-20 [1] CRAN (R 3.6.0)                    
 fansi          0.4.1    2020-01-08 [1] CRAN (R 3.6.0)                    
 forcats      * 0.5.0    2020-03-01 [1] CRAN (R 3.6.0)                    
 fs             1.4.1    2020-04-04 [1] CRAN (R 3.6.2)                    
 gdata          2.18.0   2017-06-06 [1] CRAN (R 3.6.0)                    
 generics       0.0.2    2018-11-29 [1] CRAN (R 3.6.0)                    
 ggplot2      * 3.3.0    2020-03-05 [1] CRAN (R 3.6.0)                    
 ggrepel        0.8.2    2020-03-08 [1] CRAN (R 3.6.0)                    
 glue           1.4.0    2020-04-03 [1] CRAN (R 3.6.2)                    
 gplots         3.0.3    2020-02-25 [1] CRAN (R 3.6.0)                    
 gridExtra      2.3      2017-09-09 [1] CRAN (R 3.6.0)                    
 gtable         0.3.0    2019-03-25 [1] CRAN (R 3.6.0)                    
 gtools         3.8.2    2020-03-31 [1] CRAN (R 3.6.2)                    
 haven          2.2.0    2019-11-08 [1] CRAN (R 3.6.0)                    
 hms            0.5.3    2020-01-08 [1] CRAN (R 3.6.0)                    
 httr           1.4.1    2019-08-05 [1] CRAN (R 3.6.0)                    
 igraph         1.2.5    2020-03-19 [1] CRAN (R 3.6.0)                    
 jsonlite       1.6.1    2020-02-02 [1] CRAN (R 3.6.0)                    
 KernSmooth     2.23-16  2019-10-15 [1] CRAN (R 3.6.3)                    
 knitr          1.28     2020-02-06 [1] CRAN (R 3.6.0)                    
 lattice      * 0.20-38  2018-11-04 [1] CRAN (R 3.6.3)                    
 lifecycle      0.2.0    2020-03-06 [1] CRAN (R 3.6.0)                    
 lmeSplines     1.1-10   2013-08-04 [1] CRAN (R 3.6.0)                    
 lmms         * 1.3.3    2020-04-14 [1] bitbucket (Jasmin87/lmms@cd622d7) 
 lmtest         0.9-37   2019-04-30 [1] CRAN (R 3.6.0)                    
 lubridate      1.7.8    2020-04-06 [1] CRAN (R 3.6.2)                    
 magrittr       1.5      2014-11-22 [1] CRAN (R 3.6.0)                    
 MASS         * 7.3-51.5 2019-12-20 [1] CRAN (R 3.6.3)                    
 Matrix         1.2-18   2019-11-27 [1] CRAN (R 3.6.3)                    
 matrixStats    0.56.0   2020-03-13 [1] CRAN (R 3.6.0)                    
 memoise        1.1.0    2017-04-21 [1] CRAN (R 3.6.0)                    
 mixOmics     * 6.10.9   2020-03-30 [1] Bioconductor (R 3.6.3)            
 modelr         0.1.6    2020-02-22 [1] CRAN (R 3.6.0)                    
 munsell        0.5.0    2018-06-12 [1] CRAN (R 3.6.0)                    
 nlme           3.1-144  2020-02-06 [1] CRAN (R 3.6.3)                    
 pillar         1.4.3    2019-12-20 [1] CRAN (R 3.6.0)                    
 pkgbuild       1.0.6    2019-10-09 [1] CRAN (R 3.6.0)                    
 pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 3.6.0)                    
 pkgload        1.0.2    2018-10-29 [1] CRAN (R 3.6.0)                    
 plyr           1.8.6    2020-03-03 [1] CRAN (R 3.6.0)                    
 prettyunits    1.1.1    2020-01-24 [1] CRAN (R 3.6.0)                    
 processx       3.4.2    2020-02-09 [1] CRAN (R 3.6.0)                    
 propr          4.2.6    2019-12-16 [1] CRAN (R 3.6.0)                    
 ps             1.3.2    2020-02-13 [1] CRAN (R 3.6.0)                    
 purrr        * 0.3.3    2019-10-18 [1] CRAN (R 3.6.0)                    
 R6             2.4.1    2019-11-12 [1] CRAN (R 3.6.0)                    
 rARPACK        0.11-0   2016-03-10 [1] CRAN (R 3.6.0)                    
 RColorBrewer   1.1-2    2014-12-07 [1] CRAN (R 3.6.0)                    
 Rcpp           1.0.4    2020-03-17 [1] CRAN (R 3.6.0)                    
 readr        * 1.3.1    2018-12-21 [1] CRAN (R 3.6.0)                    
 readxl         1.3.1    2019-03-13 [1] CRAN (R 3.6.0)                    
 remotes        2.1.1    2020-02-15 [1] CRAN (R 3.6.0)                    
 reprex         0.3.0    2019-05-16 [1] CRAN (R 3.6.0)                    
 reshape2       1.4.4    2020-04-09 [1] CRAN (R 3.6.2)                    
 rlang          0.4.5    2020-03-01 [1] CRAN (R 3.6.0)                    
 rprojroot      1.3-2    2018-01-03 [1] CRAN (R 3.6.0)                    
 RSpectra       0.16-0   2019-12-01 [1] CRAN (R 3.6.0)                    
 rstudioapi     0.11     2020-02-07 [1] CRAN (R 3.6.0)                    
 rvest          0.3.5    2019-11-08 [1] CRAN (R 3.6.0)                    
 scales         1.1.0    2019-11-18 [1] CRAN (R 3.6.0)                    
 sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 3.6.0)                    
 snow           0.4-3    2018-09-14 [1] CRAN (R 3.6.0)                    
 stringi        1.4.6    2020-02-17 [1] CRAN (R 3.6.0)                    
 stringr      * 1.4.0    2019-02-10 [1] CRAN (R 3.6.0)                    
 testthat       2.3.2    2020-03-02 [1] CRAN (R 3.6.0)                    
 tibble       * 3.0.0    2020-03-30 [1] CRAN (R 3.6.2)                    
 tidyr        * 1.0.2    2020-01-24 [1] CRAN (R 3.6.0)                    
 tidyselect     1.0.0    2020-01-27 [1] CRAN (R 3.6.0)                    
 tidyverse    * 1.3.0    2019-11-21 [1] CRAN (R 3.6.0)                    
 timeOmics    * 0.99.13  2020-04-14 [1] Github (abodein/timeOmics@d07808c)
 usethis      * 1.6.0    2020-04-09 [1] CRAN (R 3.6.3)                    
 vctrs          0.2.4    2020-03-10 [1] CRAN (R 3.6.0)                    
 withr          2.1.2    2018-03-15 [1] CRAN (R 3.6.0)                    
 xfun           0.13     2020-04-13 [1] CRAN (R 3.6.2)                    
 xml2           1.3.1    2020-04-09 [1] CRAN (R 3.6.2)                    
 yaml           2.2.1    2020-02-01 [1] CRAN (R 3.6.0)                    
 zoo            1.8-7    2020-01-10 [1] CRAN (R 3.6.0)                    

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

**Comment by abodein** [comment]
I have no clue here.
It's strange you don't have any error messages.
I have the same version of the `lmms` (`lmms::lmmSpline`) you have.

On my end, the vignette compiles on different computers which tells me that the problem comes from your configuration. Have you tried on a different computer?

Also, Bioconductor release is scheduled on next week, timeOmics has been accepted and should be available through this release. 
Maybe this installation mode and updated packages that come with will improve your situation.
