### ISSUE TITLE
package at risk of deprecation from bioconductor

### ISSUE THREAD

**Issue by lshep** [abodein/timeOmics_BioC#10]
Your package has been failing in devel across all platforms for over 6 weeks.  It is at risk of deprecation and removal from Bioconductor. Please fix as soon as possible to avoid deprecation.   It is also likely causing dependent package netOmics also to fail and be at risk of deprecation.

**Comment by abodein** [comment]
Hi @lshep, sorry for the delay.
I will do my best to fix this issue.
