### ISSUE TITLE
Rename blocks

### ISSUE THREAD

**Issue by siArzt** [abodein/timeOmics_BioC#2]
Hey @abodein,
Is there a possibility to change the names of the blocks in plotLong(). e.g. X = metabolome, Y = transcriptome. 

![Rplot_cut](https://user-images.githubusercontent.com/67557936/89783439-3a799a00-db17-11ea-9d98-6bfaa6225292.png)

Thank you very much for your help.
siArzt

**Comment by abodein** [comment]
Hi @siArzt, 
Sorry for this summer break delay.
I added the option `legend.block.name` in the `plotLong` function.

`devtools::install_github("abodein/timeOmics")`
```
demo <- suppressWarnings(get_demo_cluster())
plotLong(demo$pls, legend.block.name = c("new.X", "new.Y"), legend=TRUE)
```

Please let me know if you encounter any issues.
Antoine

**Comment by siArzt** [comment]
Hey @abodein, 
thanks for adding the option. Works fine! 
Simon
