### ISSUE TITLE
Package ‘lmms’ was removed from the CRAN repository.

### ISSUE THREAD

**Issue by LautenbachMJ** [abodein/timeOmics_BioC#4]
Hi, 
I cannot install timeOmics due to one of its dependencies(lmms package) is no longer available on CRAN. 

Best,
Julius

**Comment by abodein** [comment]
Hi @LautenbachMJ,
Thank you for your interest in timeOmics.
It seems that the LMMS package has been removed on 2020-09-11 but former versions can be installed from source (https://cran.r-project.org/src/contrib/Archive/lmms/).
(https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Installing-packages)
This should work to install timeOmics.

Regards,
Antoine

**Comment by LautenbachMJ** [comment]
Thank you Antoine!
