### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by jgiemza** [abodein/timeOmics_BioC#5]
Dear Antoine,

I am interested in applying the timeOmics method to my data. I have studied your vignette. I wonder if all blocks need to be longitudinal ? In my case I have four blocks and only one of them has repeated measures. Response is binary, probably not longitudinal. Will your method work on such data ?

Moreover, does mixOmics group develop an approach for longitudinal multiblock data and prediction, not only clustering ?

Thanks in advance for your answer.
Kind regards
Joanna

**Comment by abodein** [comment]
Hi @jgiemza, 

Thanks for your interest in timeOmics package.
If you are interested in the clustering of patterns, this method should work.
But all blocks should have the same number of rows.

I don't think mixOmics developers currently work on longitudinal multiblock.

Regards,
Antoine
