### ISSUE TITLE
lmms package no longer available 

### ISSUE THREAD

**Issue by RubenRBakker** [abodein/timeOmics_BioC#6]
hello timeOmics authors, 

I'm very interested in your work on multi-omics time series data. However, I found that the lmms package is no longer available for the newest version of R (v4.0.0). I've tried using devtools::install_version() to install an archived version but receive an error: 

Error: (converted from warning) package ‘ggplot2’ was built under R version 4.0.2
Execution halted

I've raised the issue here because I see some overlap between the authors of the packages and I can't open an issue on the lmms github page itself.

**Comment by abodein** [comment]
Hi @RubenRBakker,

Thank you for your interest in the package.
We are aware of this issue and are working to fix it.

As a workaround, you should be able to install it with:
 `devtools::install_github("cran/lmms")`.

Antoine

**Comment by RubenRBakker** [comment]
Hi Antoine, 

OK, if you are aware of it's all good! Just to let you know, I still get the same error as before with the workaround. But I am not in such a hurry that I need an immediate workaround, I imagine you'll have the bug fixed soon.

Thank you for your fast response! 
Ruben

<img width="901" alt="error" src="https://user-images.githubusercontent.com/17201332/106915955-f0a8ef80-6706-11eb-9444-31dd5a2c7e7b.png">
